### ISSUE TITLE
DJ2 Addons crashing with mixin version 8.4

### ISSUE THREAD

**Issue by ERBEpic** [ByThePowerOfScience/DivineJourney2Addons#6]
I tried to add performance mods to DJ2. Without any performance mods, it runs. After updating mixinbooter (and updating universaltweaks), it crashes on load with this log https://mclo.gs/xQcBSw9 . Potential causes: Divine Journey 2 Addons, Forge Mod Loader, Minecraft Forge.

I created a new instance of DJ2, removed universaltweaks, updated mixinbooter. It crashes with this log https://mclo.gs/Ots9j15 . Potential causes "Unknown"

**Comment by ChromaPIE** [comment]
haunted by the same problem

it **has** to support the latest version of mixinbooter, at least above version 8 bc mods providing modern fixes like vintagefix, hesperus and its fork alfheim do not provide a workaround version for MB7 like universaltweaks, meaning that we have to use outdated optimization mods like foamfix and phosphor, which aren't always capable of actually optimizing things.

**Comment by ByThePowerOfScience** [comment]
That crash is intentional, meant to kill the pack if something stops DJ2Addons from loading so that someone will report it and I can patch it quickly. What I didn't account for, unfortunately, was GitHub's propensity for flooding my notifications with every single issue on the DJ2 GitHub making it impossible for me to see something actually relevant to me. >->

Anyway, that's weird that it would do that.  I actually made a provision to ensure DJ2Addons would work on both the older and newer versions of Mixin, but I guess that just didn't cut it for this new thing.  Looks like MixinBooter changed how Mixin works in a way that breaks the old method of bootstrapping Mixins for everyone, not just me.

This is a bug with MixinBooter, not DJ2Addons.  I'll alert them if they don't know already.

**Comment by ByThePowerOfScience** [comment]
This is in their hands now. Thread closed.

**Comment by KorewaLidesu** [comment]
@ChromaPIE @ERBEpic 
~~Can ya test this a build?~~
~~<https://github.com/JP-HellParadise/MixinBooter/actions/runs/6683212810>~~

Please check out the next version of MixinBooter (once it is published), should have fix the incompatible with this mod.
